# Generated by Django 5.0 on 2024-01-04 09:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kitap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=50)),
                ("yazar", models.CharField(max_length=50)),
                ("aciklama", models.TextField()),
                ("eklenme_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                ("yayin_tarihi", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Yorum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yorumcu", models.CharField(max_length=50)),
                ("yorum", models.TextField()),
                ("eklenme_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "degerlendirme",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "kitap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yorumlar",
                        to="kitaplar.kitap",
                    ),
                ),
            ],
        ),
    ]
