# Generated by Django 5.0.1 on 2024-01-08 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitaplar", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="yorum",
            name="yorumcu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yorum_sahibi",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
